server:
  port: 8084
  
spring:
  data:
      mongodb:
        database: catalog_db
        port: 27017
        host: localhost
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  
queue:
  movie:
    name: Movie
  series:
    name: Series

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Catalog Service Final Materia Especialización Backend I
