server:
  port: 8082

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movie Microservice
spring:
  jpa:
    hibernate: 
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/movies
    username: root
    password: 1123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath:movie-service.sql
