server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/movies_db
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath:movie-service.sql

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movie Microservice
