server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/movies_db
    username: root
    password: ek434603
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath:movie-service.sql
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

queue:
  movie:
    name: Movie

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movie Service Final Materia Especialización Backend I
