server:
  port: 8086
  
spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: series_db
      port: 27017
      host: localhost
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
 
 queue:
  series:
    name: Series

resilience4j:
  circuitbreaker:
    instances:
      movies:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false

management:
  health:
    circuitbreakers:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Series Service Final Materia Especialización Backend I
